### ISSUE TITLE
Can't get `hk check --from-ref` working in GitHub Actions

### ISSUE THREAD

**Issue by natescherer** [jdx/hk#115]
Hello! I'm really loving hk, but I'm having trouble getting `hk check` with the `--from-ref` working in GitHub actions as a check for PRs. Here's a snippet from my workflow:

```yaml
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: hk check
        run: hk check --from-ref ${{ github.base_ref }}
```

The check is failing with this error:

```
Error: Failed to parse reference: main
Caused by:
    revspec 'main' not found; class=Reference (4); code=NotFound (-3)
Location:
    src/git.rs:516:18
```

I tried my best to untangle what was happening here but couldn't. I can see in the actions/checkout output that main is being checked out. You can see the whole run here: https://github.com/natescherer/postmodern-repo-copiertemplate/actions/runs/15405942848/job/43348587065?pr=573

Thanks!
